[package]
name = "project-diffus"
version = "0.1.0"
authors = ["Ilyar <761285+ilyar@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diffus = "0.10.0"
diffus-derive = "0.10.0"
