[package]
name = "project-diffus"
version = "0.1.0"
authors = ["Ilyar <761285+ilyar@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diffus = { version = "0.10.0", features = ["derive"] }
